# Generated by Django 6.0.2 on 2026-02-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='age_group',
            field=models.CharField(choices=[('kids', 'Niños'), ('teens', 'Jóvenes'), ('adults', 'Adultos')], default='teens', max_length=10),
        ),
    ]
